worker_processes auto; # The system will decides how man nginx worker processes should be alloted

events {
    worker_connections 1024; # This tells each individual NGINX worker process that it can open up a maximum of 1024 simultaneous network sockets at the exact same time. Gives you a safe traffic buffer
}


http {

    # Include standard mime types so browsers interpret CSS and JS files correctly
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # 1. Cluster your local Express instances
    #Load balancing configuration
    upstream express_backend {
        least_conn; #NGINX sends new traffic to whichever Express instance is least busy.

        server express-app:3001 max_fails=3 fail_timeout=10s; #This points to your Express app running inside a Docker container. If it crashes 3 times within 10 seconds, NGINX temporarily stops sending traffic to it.

        keepalive 32; #Keeps 32 open connections alive to speed up communication between NGINX and Express.
    }

    #2.  HTTP to HTTPS Redirect for Localhost
    # Here nginx server listens to the incoming requests to port 80 and redirect them to secure port 301 (https)
    server {
        listen 80;
        listen [::]:80;
        server_name localhost 127.0.0.1;

        location / {
            return 301 https://$host$request_uri;
        }
    }

    #3. HTTPS Server using mkcert Certificates
    # Nginx configuration on what happens when requests comes to port 433
    server {
        listen 443 ssl;
        listen [::]:443 ssl;
        server_name localhost;

        # Where your React production build files are placed inside the container
        root /usr/share/nginx/html;
        index index.html;

        #paths inside the docker container where certs reside
        ssl_certificate /etc/nginx/certs/localhost.pem;
        ssl_certificate_key /etc/nginx/certs/localhost-key.pem;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_session_cache shared:SSL:10m;
        ssl_session_timeout 1d;

        gzip on;
        gzip_types application/json text/plain text/css application/javascript;
        gzip_min_length 1000;

        add_header X-Frame-Options "DENY" always;
        add_header X-Content-Type-Options "nosniff" always;
        add_header X-XSS-Protection "1; mode=block" always;
        add_header Strict-Transport-Security "max-age=63072000; includeSubDomains" always;

        location / {
            # 1. Checks if the requested path matches an actual asset file (e.g., /assets/index.js)
            # 2. Checks if it matches a folder directory
            # 3. If neither, it hands off execution to the custom @backend_fallback block below
            try_files $uri $uri/ @backend_fallback;
        }

        # Named fallback block that targets your Express servers
        location @backend_fallback {
            # express_backend is the name of upstream (backend service running on port 3000)
            proxy_pass http://express_backend;
            proxy_http_version 1.1;

            proxy_set_header Connection "";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # Performance optimization for SSE (Server-Sent Events) or high load stream tests
            proxy_buffering off;
        }
    }

}

